ue:
  authsubscription:
    permanentkeyvalue: "7488250214c33e723a5dd523fc145fc0"
    opcvalue: "7488464c7c52eb6e5036234984ad0bcf"
    opvalue: "7488763286b5b9ffbdf56e1297d0887b"
    sequencenumber: "7488b3f70fc0"
  msin: "00007488"
  iddata: "UE"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai: # Single Network Slice Selection Assistance Information
    sst: 1 # Slice/Service Type (1 byte hex string, range: 0~F)
    sd: "010203" # Slice Differentiator (3 bytes hex string, range: 000000~FFFFFF)
  ranuengapid: 1
  amfuengapid: 1
  authenticationmanagementfield : "8000"
  localpublicipaddr : "192.168.59.111"
  localpublicportudpconnection : "500"
  linkgre:
    name : "gretun0"
    ipaddress: [60,60,0,1]
    mask: [255,255,255,0]
  ipsecinterfacename : "ipsec0" # IP address of IPSec virtual interface (IPsec tunnel enpoint to N3IWF)
  ipsecinterfacemark: 5 # IPSec virtual interface mark (Any value except to 0, default value is 7 if not defined)
  pdusessionid: 2
  dnnstring: "internet"

n3iwfinfo:
  ikebindaddress: "192.168.59.122" # IP address of Nwu interface (IKE) on N3IWF
  ikebindport: "500"
  ipsecifaceprotocol: "udp"

logs:
  level: "trace" # trace, info
